[2023-08-02T18:26:56.145-0500] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: orquestation.tarea1 scheduled__2022-05-15T00:00:00+00:00 [queued]>
[2023-08-02T18:26:56.150-0500] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: orquestation.tarea1 scheduled__2022-05-15T00:00:00+00:00 [queued]>
[2023-08-02T18:26:56.150-0500] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-02T18:26:56.164-0500] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): tarea1> on 2022-05-15 00:00:00+00:00
[2023-08-02T18:26:56.168-0500] {standard_task_runner.py:57} INFO - Started process 21360 to run task
[2023-08-02T18:26:56.172-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'orquestation', 'tarea1', 'scheduled__2022-05-15T00:00:00+00:00', '--job-id', '754', '--raw', '--subdir', 'DAGS_FOLDER/5.orquestation.py', '--cfg-path', '/tmp/tmp8cg59ndp']
[2023-08-02T18:26:56.173-0500] {standard_task_runner.py:85} INFO - Job 754: Subtask tarea1
[2023-08-02T18:26:56.206-0500] {task_command.py:410} INFO - Running <TaskInstance: orquestation.tarea1 scheduled__2022-05-15T00:00:00+00:00 [running]> on host pop-os.localdomain
[2023-08-02T18:26:56.255-0500] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='orquestation' AIRFLOW_CTX_TASK_ID='tarea1' AIRFLOW_CTX_EXECUTION_DATE='2022-05-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-05-15T00:00:00+00:00'
[2023-08-02T18:26:56.257-0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-02T18:26:56.257-0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "sleep 2 && echo'Tarea1'"]
[2023-08-02T18:26:56.268-0500] {subprocess.py:86} INFO - Output:
[2023-08-02T18:26:58.272-0500] {subprocess.py:93} INFO - /usr/bin/bash: line 1: echoTarea1: command not found
[2023-08-02T18:26:58.273-0500] {subprocess.py:97} INFO - Command exited with return code 127
[2023-08-02T18:26:58.296-0500] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-08-02T18:26:58.419-0500] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=orquestation, task_id=tarea1, execution_date=20220515T000000, start_date=20230802T232656, end_date=20230802T232658
[2023-08-02T18:26:58.439-0500] {standard_task_runner.py:104} ERROR - Failed to execute job 754 for task tarea1 (Bash command failed. The command returned a non-zero exit code 127.; 21360)
[2023-08-02T18:26:58.481-0500] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-02T18:26:58.498-0500] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
