[2023-08-03T13:48:27.083-0500] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitoring.tarea2 scheduled__2023-08-02T00:00:00+00:00 [queued]>
[2023-08-03T13:48:27.131-0500] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitoring.tarea2 scheduled__2023-08-02T00:00:00+00:00 [queued]>
[2023-08-03T13:48:27.133-0500] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-03T13:48:27.262-0500] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): tarea2> on 2023-08-02 00:00:00+00:00
[2023-08-03T13:48:27.344-0500] {standard_task_runner.py:57} INFO - Started process 25754 to run task
[2023-08-03T13:48:27.422-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'monitoring', 'tarea2', 'scheduled__2023-08-02T00:00:00+00:00', '--job-id', '939', '--raw', '--subdir', 'DAGS_FOLDER/monitoring.py', '--cfg-path', '/tmp/tmpxazb0br4']
[2023-08-03T13:48:27.445-0500] {standard_task_runner.py:85} INFO - Job 939: Subtask tarea2
[2023-08-03T13:48:28.217-0500] {task_command.py:410} INFO - Running <TaskInstance: monitoring.tarea2 scheduled__2023-08-02T00:00:00+00:00 [running]> on host pop-os.localdomain
[2023-08-03T13:48:28.823-0500] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='monitoring' AIRFLOW_CTX_TASK_ID='tarea2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-02T00:00:00+00:00'
[2023-08-03T13:48:28.838-0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-03T13:48:28.849-0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "sleep 2 && echo 'Tarea 2"]
[2023-08-03T13:48:28.942-0500] {subprocess.py:86} INFO - Output:
[2023-08-03T13:48:28.954-0500] {subprocess.py:93} INFO - /usr/bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-08-03T13:48:28.955-0500] {subprocess.py:93} INFO - /usr/bin/bash: -c: line 2: syntax error: unexpected end of file
[2023-08-03T13:48:28.960-0500] {subprocess.py:97} INFO - Command exited with return code 2
[2023-08-03T13:48:29.058-0500] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-08-03T13:48:30.550-0500] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=monitoring, task_id=tarea2, execution_date=20230802T000000, start_date=20230803T184827, end_date=20230803T184830
[2023-08-03T13:48:30.691-0500] {standard_task_runner.py:104} ERROR - Failed to execute job 939 for task tarea2 (Bash command failed. The command returned a non-zero exit code 2.; 25754)
[2023-08-03T13:48:31.393-0500] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-03T13:48:31.614-0500] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-03T13:58:31.360-0500] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitoring.tarea2 scheduled__2023-08-02T00:00:00+00:00 [queued]>
[2023-08-03T13:58:31.419-0500] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitoring.tarea2 scheduled__2023-08-02T00:00:00+00:00 [queued]>
[2023-08-03T13:58:31.420-0500] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-03T13:58:31.506-0500] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): tarea2> on 2023-08-02 00:00:00+00:00
[2023-08-03T13:58:31.542-0500] {standard_task_runner.py:57} INFO - Started process 27201 to run task
[2023-08-03T13:58:31.570-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'monitoring', 'tarea2', 'scheduled__2023-08-02T00:00:00+00:00', '--job-id', '939', '--raw', '--subdir', 'DAGS_FOLDER/monitoring.py', '--cfg-path', '/tmp/tmp401lujgx']
[2023-08-03T13:58:31.581-0500] {standard_task_runner.py:85} INFO - Job 939: Subtask tarea2
[2023-08-03T13:58:31.870-0500] {task_command.py:410} INFO - Running <TaskInstance: monitoring.tarea2 scheduled__2023-08-02T00:00:00+00:00 [running]> on host pop-os.localdomain
[2023-08-03T13:58:32.298-0500] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='monitoring' AIRFLOW_CTX_TASK_ID='tarea2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-02T00:00:00+00:00'
[2023-08-03T13:58:32.310-0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-03T13:58:32.314-0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "sleep 2 && echo 'Tarea 2'"]
[2023-08-03T13:58:32.400-0500] {subprocess.py:86} INFO - Output:
[2023-08-03T13:58:34.417-0500] {subprocess.py:93} INFO - Tarea 2
[2023-08-03T13:58:34.419-0500] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-03T13:58:35.228-0500] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=monitoring, task_id=tarea2, execution_date=20230802T000000, start_date=20230803T185831, end_date=20230803T185835
[2023-08-03T13:58:35.383-0500] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-03T13:58:35.574-0500] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
